package com.nutriai.ui.move

/**
 * AUTO-GENERATED. Fixes for exercises that used to share (or wrongly borrow) another exercise's GIF:
 *  - [gifPathBySlug]: exercises whose exact GIF exists in our repo (name slug -> path inside kaizen-exercise-media, no extension).
 *  - [hiddenFromLibrary]: library-only entries that either duplicate another entry (same exercise, different name) or have no
 *    GIF that shows them correctly. They are hidden from the Library list; exercises the app plans itself are never hidden.
 */
object ExerciseDemoOverrides {
    val gifPathBySlug: Map<String, String> = mapOf(
        "bench-press-with-bands" to "anatome-gifs/Bench_Press_-_With_Bands",
        "bosu-ball-cable-crunch-with-side-bends" to "anatome-gifs/Bosu_Ball_Cable_Crunch_With_Side_Bends",
        "calf-raise" to "anatome-gifs/Calf_Raise_On_A_Dumbbell",
        "chest-dips" to "anatome-gifs/Dips_-_Chest_Version",
        "crunch" to "anatome-gifs/Crunches",
        "decline-bench-press" to "pectorals/barbell-decline-bench-press",
        "drop-push" to "anatome-gifs/Drop_Push",
        "farmer-s-walk" to "anatome-gifs/Farmers_Walk",
        "gironda-sternum-chins" to "anatome-gifs/Gironda_Sternum_Chins",
        "glute-bridge" to "glutes/barbell-glute-bridge",
        "isometric-chest-squeezes" to "anatome-gifs/Isometric_Chest_Squeezes",
        "lateral-lunge" to "glutes/barbell-lateral-lunge",
        "lying-leg-raise" to "abs/band-lying-straight-leg-raise",
        "mountain-climbers" to "anatome-gifs/Mountain_Climbers",
        "overhead-tricep-extension" to "anatome-gifs/Triceps_Overhead_Extension_with_Rope",
        "pendlay-row" to "upper-back/barbell-pendlay-row",
        "rear-delt-fly" to "anatome-gifs/Cable_Rear_Delt_Fly",
        "resistance-band-curl" to "biceps/resistance-band-seated-biceps-curl",
        "runner-s-stretch" to "anatome-gifs/Runners_Stretch",
        "seated-twist" to "abs/band-seated-twist",
        "shoulder-press-with-bands" to "anatome-gifs/Shoulder_Press_-_With_Bands",
        "side-to-side-chins" to "anatome-gifs/Side_To_Side_Chins",
        "single-arm-dumbbell-row" to "anatome-gifs/One-Arm_Dumbbell_Row",
        "squat-with-bands" to "anatome-gifs/Squat_with_Bands",
        "squats-with-bands" to "anatome-gifs/Squat_with_Bands",
        "stiff-leg-deadlift" to "glutes/band-stiff-leg-deadlift",
        "tricep-pushdown" to "anatome-gifs/Triceps_Pushdown"
    )

    val hiddenFromLibrary: Set<String> = setOf(
        "advanced-kettlebell-windmill",
        "alternating-kettlebell-press",
        "alternating-kettlebell-row",
        "arnold-dumbbell-press",
        "band-bicycle-crunch",
        "barbell-close-grip-bench-press",
        "barbell-front-squat",
        "barbell-incline-bench-press",
        "barbell-squat-to-a-bench",
        "barbell-upright-row",
        "barbell-wrist-curl",
        "bent-over-barbell-row",
        "bent-arm-barbell-pullover",
        "bent-knee-hip-raise",
        "bodyweight-standing-calf-raise",
        "cable-deadlifts",
        "cable-rope-rear-delt-rows",
        "cable-seated-row",
        "cable-shrugs",
        "calf-stretch-hands-against-wall",
        "chin-up",
        "close-grip-barbell-bench-press",
        "close-grip-dumbbell-press",
        "close-grip-push-up-off-of-a-dumbbell",
        "close-grip-standing-barbell-curl",
        "decline-barbell-bench-press",
        "decline-dumbbell-bench-press",
        "decline-dumbbell-triceps-extension",
        "decline-push-up",
        "diamond-push-up",
        "donkey-calf-raises",
        "double-kettlebell-alternating-hang-clean",
        "double-kettlebell-jerk",
        "double-kettlebell-push-press",
        "double-kettlebell-snatch",
        "double-kettlebell-windmill",
        "dumbbell-alternate-bicep-curl",
        "dumbbell-arnold-press",
        "dumbbell-bench-press-with-neutral-grip",
        "dumbbell-bicep-curl",
        "dumbbell-biceps-curl",
        "dumbbell-concentration-curl",
        "dumbbell-front-raise",
        "dumbbell-hammer-curl",
        "dumbbell-incline-curl",
        "dumbbell-incline-fly",
        "dumbbell-lateral-raise",
        "dumbbell-lunges",
        "dumbbell-squat-to-a-bench",
        "dumbbell-step-up",
        "ez-bar-curl",
        "extended-range-one-arm-kettlebell-floor-press",
        "flat-bench-leg-pull-in",
        "flat-bench-lying-leg-raise",
        "front-barbell-squat",
        "front-barbell-squat-to-a-bench",
        "front-cable-raise",
        "front-dumbbell-raise",
        "hip-lift-with-band",
        "incline-push-up",
        "incline-push-up-close-grip",
        "incline-push-up-reverse-grip",
        "kneeling-cable-triceps-extension",
        "landmine-180-s",
        "lever-back-extension",
        "lever-leg-extension",
        "lever-lying-leg-curl",
        "lever-t-bar-row",
        "lying-dumbbell-tricep-extension",
        "lying-supine-dumbbell-curl",
        "machine-inner-chest-press",
        "mixed-grip-chin",
        "oblique-crunches-on-the-floor",
        "one-leg-barbell-squat",
        "one-arm-kettlebell-clean-and-jerk",
        "one-arm-kettlebell-floor-press",
        "one-arm-kettlebell-jerk",
        "one-arm-kettlebell-military-press-to-the-side",
        "one-arm-kettlebell-push-press",
        "one-arm-kettlebell-row",
        "one-arm-kettlebell-snatch",
        "one-arm-medicine-ball-slam",
        "overhead-cable-curl",
        "palms-up-barbell-wrist-curl-over-a-bench",
        "pull-up",
        "push-up",
        "push-up-to-side-plank",
        "reverse-barbell-curl",
        "reverse-barbell-preacher-curls",
        "reverse-cable-curl",
        "seated-barbell-twist",
        "seated-cable-rows",
        "seated-close-grip-concentration-barbell-curl",
        "seated-dumbbell-curl",
        "seated-dumbbell-inner-biceps-curl",
        "seated-dumbbell-palms-up-wrist-curl",
        "side-neck-stretch",
        "single-leg-squat-pistol-male",
        "smith-incline-shoulder-raise",
        "split-squats",
        "standing-barbell-calf-raise",
        "standing-bent-over-one-arm-dumbbell-triceps-extension",
        "standing-bent-over-two-arm-dumbbell-triceps-extension",
        "standing-cable-lift",
        "standing-dumbbell-calf-raise",
        "standing-dumbbell-reverse-curl",
        "standing-dumbbell-triceps-extension",
        "standing-front-barbell-raise-over-head",
        "standing-one-arm-dumbbell-curl-over-incline-bench",
        "standing-overhead-barbell-triceps-extension",
        "standing-palm-in-one-arm-dumbbell-press",
        "standing-palms-in-dumbbell-press",
        "stationary-bike-run-v-3",
        "stiff-leg-barbell-good-morning",
        "straight-arm-dumbbell-pullover",
        "straight-arm-pulldown",
        "two-arm-kettlebell-clean",
        "two-arm-kettlebell-military-press",
        "two-arm-kettlebell-row",
        "underhand-cable-pulldowns",
        "upright-barbell-row",
        "upright-cable-row",
        "wide-grip-decline-barbell-pullover",
        "wide-grip-standing-barbell-curl",
        "world-greatest-stretch"
    )
}
