package com.nutriai.ui.move

// AUTO-GENERATED: free-exercise-db (public domain) slug per exercise name. Two stills per exercise
// (0.jpg start, 1.jpg end) are alternated client-side into an animated movement demo. Keys are
// lower-cased exercise names; unmatched exercises fall back to the bundled muscle diagram.
object ExerciseDemoMap {
    const val BASE = "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/"
    private val slugs: Map<String, String> = mapOf(
        "archer push-ups" to "Pushups",
        "arnold press" to "Arnold_Dumbbell_Press",
        "back squat" to "Barbell_Squat",
        "backpack high-row" to "Kneeling_High_Pulley_Row",
        "backpack rows" to "Seated_Cable_Rows",
        "backpack shrugs" to "Cable_Shrugs",
        "band chest press" to "Cable_Chest_Press",
        "band rows" to "Seated_Cable_Rows",
        "barbell bench press" to "Barbell_Bench_Press_-_Medium_Grip",
        "barbell curl" to "Barbell_Curl",
        "barbell deadlift" to "Barbell_Deadlift",
        "barbell lunge" to "Barbell_Lunge",
        "barbell row" to "Bent_Over_Barbell_Row",
        "barbell shrugs" to "Barbell_Shrug",
        "bench dips" to "Bench_Dips",
        "bench press" to "Barbell_Bench_Press_-_Medium_Grip",
        "bicycle crunch" to "Air_Bike",
        "bicycle crunches" to "Air_Bike",
        "bodyweight squats" to "Bodyweight_Squat",
        "bulgarian split squat" to "Split_Squats",
        "cable crunch" to "Cable_Crunch",
        "cable fly" to "Cable_Crossover",
        "cable lateral raise" to "Side_Lateral_Raise",
        "cable overhead extension" to "Cable_Rope_Overhead_Triceps_Extension",
        "cable row" to "Seated_Cable_Rows",
        "calf raise" to "Seated_Calf_Raise",
        "calf raises" to "Seated_Calf_Raise",
        "chair dips" to "Bench_Dips",
        "chest dips" to "Dips_-_Chest_Version",
        "clap push-ups" to "Pushups",
        "concentration curl" to "Concentration_Curls",
        "deadlift" to "Barbell_Deadlift",
        "decline press" to "Decline_Barbell_Bench_Press",
        "decline push-ups" to "Decline_Push-Up",
        "diamond push-ups" to "Pushups",
        "doorway rows" to "Seated_Cable_Rows",
        "dumbbell bench press" to "Dumbbell_Bench_Press",
        "dumbbell curl" to "Dumbbell_Bicep_Curl",
        "dumbbell curls" to "Dumbbell_Bicep_Curl",
        "dumbbell press" to "Dumbbell_Bench_Press",
        "dumbbell shoulder press" to "Dumbbell_Shoulder_Press",
        "dumbbell shrugs" to "Dumbbell_Shrug",
        "face pull" to "Face_Pull",
        "flat dumbbell press" to "Dumbbell_Bench_Press",
        "front raise" to "Front_Dumbbell_Raise",
        "front squat" to "Front_Barbell_Squat",
        "goblet squat" to "Goblet_Squat",
        "hack squat" to "Hack_Squat",
        "hammer curl" to "Hammer_Curls",
        "hanging knee raise" to "Hanging_Leg_Raise",
        "hanging leg raise" to "Hanging_Leg_Raise",
        "hindu push-ups" to "Pushups",
        "incline barbell press" to "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "incline cable press" to "Incline_Cable_Chest_Press",
        "incline dumbbell curl" to "Alternate_Incline_Dumbbell_Curl",
        "incline dumbbell press" to "Incline_Dumbbell_Press",
        "incline press" to "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "inverted rows" to "Inverted_Row",
        "jm press" to "JM_Press",
        "jump squats" to "Freehand_Jump_Squat",
        "knee push-ups" to "Pushups",
        "lat pulldown" to "One_Arm_Lat_Pulldown",
        "lat pulldown with a band" to "One_Arm_Lat_Pulldown",
        "lateral raise" to "Side_Lateral_Raise",
        "leg curl" to "Seated_Leg_Curl",
        "leg extension" to "Single-Leg_Leg_Extension",
        "leg press" to "Leg_Press",
        "leg raises" to "Front_Leg_Raises",
        "machine chest press" to "Cable_Chest_Press",
        "machine shoulder press" to "Alternating_Cable_Shoulder_Press",
        "overhead barbell press" to "Barbell_Shoulder_Press",
        "overhead extension" to "Cable_Rope_Overhead_Triceps_Extension",
        "pike push-ups" to "Pushups",
        "plank" to "Plank",
        "preacher curl" to "Cable_Preacher_Curl",
        "push press" to "Push_Press",
        "rack pulls" to "Rack_Pulls",
        "reverse curl" to "Reverse_Cable_Curl",
        "reverse wrist curl" to "Cable_Wrist_Curl",
        "romanian deadlift" to "Romanian_Deadlift",
        "rope hammer curl" to "Cable_Hammer_Curls_-_Rope_Attachment",
        "rope pushdown" to "Triceps_Pushdown_-_Rope_Attachment",
        "scapular push-ups" to "Pushups",
        "seated cable row" to "Seated_Cable_Rows",
        "seated calf raise" to "Seated_Calf_Raise",
        "seated row" to "Seated_Cable_Rows",
        "side plank" to "Push_Up_to_Side_Plank",
        "spider curl" to "Spider_Curl",
        "standing calf raise" to "Standing_Calf_Raises",
        "standing knee raises" to "Bent-Knee_Hip_Raise",
        "svend press" to "Svend_Press",
        "towel door rows" to "Seated_Cable_Rows",
        "upright row" to "Upright_Cable_Row",
        "weighted dips" to "Weighted_Bench_Dip",
        "weighted pull-ups" to "Weighted_Pull_Ups",
        "wide push-ups" to "Push-Up_Wide",
        "wrist curl" to "Cable_Wrist_Curl",
        "zottman curl" to "Zottman_Curl",
    )

    /** [startUrl, endUrl] for an exercise name, or null when we have no demo for it. */
    fun framesFor(name: String): Pair<String, String>? {
        val slug = slugs[name.trim().lowercase()] ?: return null
        return (BASE + slug + "/0.jpg") to (BASE + slug + "/1.jpg")
    }
}
