package com.nutriai.ui.move

// AUTO-GENERATED: animated exercise-demo GIF per exercise, from ExerciseGymGifsDB (1300+ GIFs, free
// jsDelivr CDN). Keys are a CANONICAL form of the exercise name (lower-cased, apostrophes/punct
// stripped, simple plurals singularised, tokens sorted) so "Squat jumps" and "Jump squats" both
// resolve. Value = dataset id ("<muscle>/<slug>"). Unmatched → bundled muscle diagram fallback.
object ExerciseDemoMap {
    const val BASE = "https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/"
    private val stop = setOf("the", "a", "to", "of", "and", "on", "with", "up")
    private val ids: Map<String, String> = mapOf(
        "30s 90s conditioning e easy g hard hiit" to "cardio/burpee",
        "3s down push slow ups" to "pectorals/push-up",
        "60 90s between rest set" to "hamstrings/world-greatest-stretch",
        "ab rollout wheel" to "hamstrings/world-greatest-stretch",
        "abs crunch lower reverse" to "cardio/high-knee-against-wall",
        "abs leg" to "hamstrings/world-greatest-stretch",
        "advanced leg" to "hamstrings/world-greatest-stretch",
        "advanced lower" to "hamstrings/world-greatest-stretch",
        "advanced pull" to "hamstrings/world-greatest-stretch",
        "advanced push" to "hamstrings/world-greatest-stretch",
        "advanced upper" to "hamstrings/world-greatest-stretch",
        "angel reverse snow" to "delts/dumbbell-reverse-fly",
        "anti bird dog rotation" to "abs/dead-bug",
        "anti rotation russian twist" to "hamstrings/world-greatest-stretch",
        "apart arm band circle pull" to "delts/dumbbell-reverse-fly",
        "archer push ups" to "pectorals/push-up",
        "arm circle hip opener" to "delts/dumbbell-reverse-fly",
        "arm dumbbell row single" to "delts/dumbbell-one-arm-upright-row",
        "arm pulldown straight" to "lats/cable-straight-arm-pulldown",
        "arm pushdown single" to "hamstrings/world-greatest-stretch",
        "arnold press" to "delts/dumbbell-arnold-press",
        "assisted band pull ups" to "lats/band-assisted-pull-up",
        "assisted pistol squat" to "abs/assisted-sit-up",
        "at friendly knee leg one split squat time" to "hamstrings/world-greatest-stretch",
        "b body full" to "hamstrings/world-greatest-stretch",
        "back" to "upper-back/upper-back-stretch",
        "back bicep pull" to "biceps/biceps-pull-up",
        "back bridge friendly glute hip thrust" to "upper-back/upper-back-stretch",
        "back bug dead friendly" to "upper-back/upper-back-stretch",
        "back extension" to "spine/lever-back-extension",
        "back squat" to "glutes/barbell-full-squat-back-pov",
        "backpack curl" to "abs/curl-up",
        "backpack curl hammer" to "upper-back/upper-back-stretch",
        "backpack fly reverse" to "delts/dumbbell-reverse-fly",
        "backpack high row" to "upper-back/lever-high-row",
        "backpack row" to "upper-back/inverted-row",
        "backpack shrug" to "traps/barbell-shrug",
        "band chest press" to "pectorals/resistance-band-seated-chest-press",
        "band chest press resistance" to "pectorals/resistance-band-seated-chest-press",
        "band curl" to "biceps/band-concentration-curl",
        "band dislocate shoulder towel" to "delts/dumbbell-reverse-fly",
        "band good morning" to "hamstrings/world-greatest-stretch",
        "band lat pulldown" to "lats/band-underhand-pulldown",
        "band pushdown" to "hamstrings/world-greatest-stretch",
        "band row" to "glutes/band-squat-row",
        "bar curl ez" to "biceps/ez-bar-biceps-curl-with-arm-blaster",
        "bar deadlift trap" to "glutes/trap-bar-deadlift",
        "bar row t" to "upper-back/lever-t-bar-row",
        "barbell bench press" to "pectorals/barbell-bench-press",
        "barbell curl" to "biceps/barbell-curl",
        "barbell incline press" to "pectorals/barbell-incline-bench-press",
        "barbell overhead press" to "delts/barbell-seated-overhead-press",
        "barbell row" to "upper-back/barbell-bent-over-row",
        "barbell shrug" to "traps/barbell-shrug",
        "battle rope" to "delts/battling-ropes",
        "bench close grip press" to "triceps/barbell-close-grip-bench-press",
        "bench dip" to "triceps/bench-dip-on-floor",
        "bench dip feet" to "hamstrings/world-greatest-stretch",
        "bench dumbbell press" to "pectorals/dumbbell-bench-press",
        "bench press" to "pectorals/barbell-bench-press",
        "bicep forearm" to "hamstrings/world-greatest-stretch",
        "bicycle crunch" to "abs/band-bicycle-crunch",
        "bicycle crunche" to "abs/band-bicycle-crunch",
        "bike interval" to "cardio/high-knee-against-wall",
        "bird dog" to "abs/dead-bug",
        "body c full" to "hamstrings/world-greatest-stretch",
        "body child fold forward full pose" to "hamstrings/hamstring-stretch",
        "body circuit full" to "cardio/high-knee-against-wall",
        "body cross shoulder stretch" to "hamstrings/world-greatest-stretch",
        "body full" to "triceps/body-up",
        "body full stretching" to "hamstrings/world-greatest-stretch",
        "body full weight" to "hamstrings/world-greatest-stretch",
        "body hold hollow" to "hamstrings/world-greatest-stretch",
        "bodyweight circuit" to "cardio/high-knee-against-wall",
        "bodyweight equipment needed no only" to "hamstrings/world-greatest-stretch",
        "bodyweight goblet squat" to "quads/squat-to-overhead-reach",
        "bodyweight squat" to "quads/squat-to-overhead-reach",
        "box jump" to "hamstrings/world-greatest-stretch",
        "bridge glute" to "glutes/low-glute-bridge-on-floor",
        "bridge glute leg single" to "glutes/single-leg-bridge-with-outstretched-leg",
        "brisk cardio cycle state steady walk" to "cardio/walking-on-incline-treadmill",
        "brisk cycle walk" to "cardio/high-knee-against-wall",
        "brisk jog walk" to "cardio/walking-on-incline-treadmill",
        "broad jump" to "hamstrings/world-greatest-stretch",
        "bug controlled dead slow" to "hamstrings/world-greatest-stretch",
        "bug dead" to "abs/dead-bug",
        "bulgarian chair split squat" to "quads/split-squats",
        "bulgarian split squat" to "quads/split-squats",
        "burnout push" to "pectorals/push-up",
        "burpee" to "cardio/burpee",
        "cable crossover" to "upper-back/cable-rope-crossover-seated-row",
        "cable crunch" to "abs/cable-reverse-crunch",
        "cable curl" to "biceps/cable-curl",
        "cable extension overhead" to "triceps/cable-high-pulley-overhead-tricep-extension",
        "cable fly" to "pectorals/cable-decline-fly",
        "cable incline press" to "pectorals/cable-one-arm-incline-press",
        "cable lateral leaning" to "delts/cable-lateral-raise",
        "cable lateral raise" to "delts/dumbbell-lateral-raise",
        "cable pullover" to "lats/cable-lying-extension-pullover-with-rope-attachment",
        "cable row" to "delts/cable-upright-row",
        "cable row seated" to "upper-back/cable-seated-row",
        "calf raise" to "calves/bodyweight-standing-calf-raise",
        "calf raise seated" to "calves/barbell-seated-calf-raise",
        "calf raise standing" to "calves/bodyweight-standing-calf-raise",
        "cardio circuit" to "cardio/high-knee-against-wall",
        "cardio core" to "cardio/high-knee-against-wall",
        "cardio core steady" to "cardio/walking-on-incline-treadmill",
        "cardio jog light march spot" to "cardio/high-knee-against-wall",
        "cardio mobility" to "cardio/high-knee-against-wall",
        "cardio steady" to "cardio/walking-on-incline-treadmill",
        "chair dip" to "pectorals/chest-dip",
        "chest" to "pectorals/chest-dip",
        "chest dip" to "pectorals/chest-dip",
        "chest doorway stretch" to "pectorals/behind-head-chest-stretch",
        "chest machine press" to "pectorals/machine-inner-chest-press",
        "chest push shoulder tricep" to "triceps/triceps-dip",
        "chest row supported" to "upper-back/inverted-row",
        "circle greatest hip stretch world" to "hamstrings/world-greatest-stretch",
        "circuit core" to "cardio/high-knee-against-wall",
        "clap push ups" to "pectorals/push-up",
        "climber mountain" to "cardio/mountain-climber",
        "close grip push ups" to "pectorals/push-up",
        "complex plank" to "hamstrings/world-greatest-stretch",
        "concentration curl" to "biceps/dumbbell-concentration-curl",
        "conditioning finisher" to "cardio/burpee",
        "conditioning hiit" to "cardio/high-knee-against-wall",
        "core hiit" to "cardio/high-knee-against-wall",
        "core leg" to "hamstrings/world-greatest-stretch",
        "core lower strength" to "hamstrings/world-greatest-stretch",
        "core mobility" to "hamstrings/world-greatest-stretch",
        "core tricep" to "hamstrings/world-greatest-stretch",
        "core walk" to "glutes/monster-walk",
        "crusher skull" to "hamstrings/world-greatest-stretch",
        "curl dumbbell" to "biceps/dumbbell-biceps-curl",
        "curl dumbbell incline" to "biceps/dumbbell-incline-curl",
        "curl hammer" to "biceps/dumbbell-hammer-curl",
        "curl hammer rope" to "biceps/cable-hammer-curl-with-rope",
        "curl isometric towel" to "abs/curl-up",
        "curl leg" to "biceps/biceps-leg-concentration-curl",
        "curl nordic" to "abs/curl-up",
        "curl preacher" to "biceps/barbell-preacher-curl",
        "curl reverse" to "biceps/barbell-reverse-curl",
        "curl reverse wrist" to "forearms/barbell-reverse-wrist-curl",
        "curl spider" to "biceps/dumbbell-reverse-spider-curl",
        "curl towel" to "abs/curl-up",
        "curl wrist" to "forearms/barbell-wrist-curl",
        "curl zottman" to "biceps/dumbbell-zottman-curl",
        "curtsy lunge" to "glutes/dumbbell-lunge",
        "cycle incline walk" to "cardio/high-knee-against-wall",
        "deadlift" to "glutes/barbell-deadlift",
        "deadlift romanian" to "glutes/barbell-romanian-deadlift",
        "deck fly pec" to "pectorals/dumbbell-fly",
        "deck pec reverse" to "hamstrings/world-greatest-stretch",
        "decline press" to "pectorals/dumbbell-decline-hammer-press",
        "decline push ups" to "pectorals/push-up",
        "delt fly rear" to "delts/dumbbell-reverse-fly",
        "delt pull rear" to "delts/dumbbell-reverse-fly",
        "delt rear row" to "delts/barbell-rear-delt-row",
        "diamond push ups" to "pectorals/push-up",
        "dip weighted" to "triceps/weighted-tricep-dips",
        "door row towel" to "upper-back/bodyweight-squatting-row-with-towel",
        "doorway row" to "upper-back/inverted-row",
        "dumbbell flat press" to "delts/dumbbell-arnold-press",
        "dumbbell floor friendly press shoulder" to "delts/dumbbell-reverse-fly",
        "dumbbell incline press" to "pectorals/dumbbell-incline-alternate-press",
        "dumbbell leg rdl single" to "hamstrings/world-greatest-stretch",
        "dumbbell press" to "delts/dumbbell-arnold-press",
        "dumbbell press shoulder" to "delts/dumbbell-seated-shoulder-press",
        "dumbbell shrug" to "traps/dumbbell-shrug",
        "elevated feet progress push ups" to "pectorals/push-up",
        "elevated feet push ups" to "pectorals/push-up",
        "explosive push" to "hamstrings/world-greatest-stretch",
        "extension leg" to "quads/lever-leg-extension",
        "extension overhead" to "triceps/barbell-seated-overhead-triceps-extension",
        "face pull" to "delts/dumbbell-reverse-fly",
        "face pull towel" to "delts/dumbbell-reverse-fly",
        "feet floor inverted row" to "abs/crunch-floor",
        "feet hip thrust" to "quads/intermediate-hip-flexor-and-quad-stretch",
        "flexor glute hip stretch" to "quads/intermediate-hip-flexor-and-quad-stretch",
        "flow mobility" to "hamstrings/world-greatest-stretch",
        "fly reverse" to "delts/dumbbell-reverse-fly",
        "friday" to "hamstrings/world-greatest-stretch",
        "friendly knee lunge reverse" to "glutes/dumbbell-lunge",
        "friendly landmine press shoulder" to "delts/dumbbell-reverse-fly",
        "front leg side swing" to "lats/side-to-side-chin",
        "front raise" to "delts/dumbbell-front-raise",
        "front squat" to "glutes/barbell-front-squat",
        "grip pulldown wide" to "lats/cable-wide-grip-rear-pulldown-behind-neck",
        "hack squat" to "glutes/barbell-hack-squat",
        "hamstring quad standing stretch" to "hamstrings/standing-hamstring-and-calf-stretch-with-strap",
        "hand incline push surface ups" to "pectorals/push-up",
        "hanging knee raise" to "abs/hanging-oblique-knee-raise",
        "hanging leg lying raise" to "abs/hanging-leg-raise",
        "hanging leg raise" to "abs/hanging-leg-raise",
        "high knee" to "cardio/high-knee-against-wall",
        "hindu push ups" to "pectorals/push-up",
        "hold onto split squat support" to "glutes/potty-squat-with-support",
        "hold superman" to "hamstrings/world-greatest-stretch",
        "hypertrophy lower" to "hamstrings/world-greatest-stretch",
        "hypertrophy upper" to "hamstrings/world-greatest-stretch",
        "incline press" to "pectorals/barbell-incline-bench-press",
        "interval rowing" to "upper-back/upper-back-stretch",
        "inverted row" to "upper-back/inverted-row",
        "inverted row table" to "upper-back/upper-back-stretch",
        "jack jumping" to "cardio/star-jump-male",
        "jack plank" to "cardio/jack-burpee",
        "jm press" to "triceps/barbell-jm-bench-press",
        "jump lunge" to "glutes/lunge-with-jump",
        "jump skater" to "cardio/skater-hops",
        "jump squat" to "glutes/jump-squat",
        "kettlebell swing" to "glutes/kettlebell-swing",
        "kickback" to "upper-back/upper-back-stretch",
        "knee push ups" to "pectorals/push-up",
        "knee raise standing" to "abs/hanging-oblique-knee-raise",
        "lat pulldown" to "lats/twin-handle-parallel-grip-lat-pulldown",
        "lateral raise" to "delts/dumbbell-lateral-raise",
        "leg" to "hamstrings/world-greatest-stretch",
        "leg press" to "glutes/smith-leg-press",
        "leg raise" to "abs/hanging-leg-raise",
        "leg rdl single" to "hamstrings/world-greatest-stretch",
        "leg volume" to "hamstrings/world-greatest-stretch",
        "light walk" to "glutes/monster-walk",
        "lower" to "hamstrings/world-greatest-stretch",
        "lower power" to "hamstrings/power-clean",
        "lower strength" to "hamstrings/world-greatest-stretch",
        "lunge reverse" to "glutes/dumbbell-lunge",
        "lunge walking" to "glutes/dumbbell-lunge",
        "machine press shoulder" to "delts/dumbbell-seated-shoulder-press",
        "monday" to "hamstrings/world-greatest-stretch",
        "overhead press" to "delts/barbell-seated-overhead-press",
        "pike push ups" to "pectorals/push-up",
        "planche pseudo push ups" to "pectorals/push-up",
        "plank" to "abs/front-plank-with-twist",
        "plank reach" to "hamstrings/world-greatest-stretch",
        "plank side" to "abs/push-up-to-side-plank",
        "plyometric" to "hamstrings/world-greatest-stretch",
        "press push" to "delts/dumbbell-push-press",
        "press svend" to "pectorals/weighted-svend-press",
        "program" to "hamstrings/world-greatest-stretch",
        "prone t w y" to "delts/dumbbell-reverse-fly",
        "pull rack" to "hamstrings/world-greatest-stretch",
        "pull shoulder" to "delts/dumbbell-reverse-fly",
        "pull superman" to "hamstrings/world-greatest-stretch",
        "pull ups weighted" to "lats/weighted-pull-up",
        "pull volume" to "hamstrings/world-greatest-stretch",
        "push scapular ups" to "pectorals/push-up",
        "push tempo" to "hamstrings/world-greatest-stretch",
        "push ups" to "pectorals/push-up",
        "push ups wide" to "pectorals/push-up",
        "push volume" to "hamstrings/world-greatest-stretch",
        "pushdown rope" to "triceps/cable-pushdown-with-rope-attachment",
        "pushdown tricep" to "hamstrings/world-greatest-stretch",
        "quad standing stretch" to "quads/intermediate-hip-flexor-and-quad-stretch",
        "raise y" to "upper-back/dumbbell-incline-y-raise",
        "recovery rest" to "hamstrings/world-greatest-stretch",
        "rest" to "hamstrings/world-greatest-stretch",
        "row seated" to "upper-back/cable-seated-row",
        "row upright" to "delts/barbell-upright-row",
        "run steady" to "cardio/walking-on-incline-treadmill",
        "russian twist" to "abs/russian-twist",
        "saturday" to "hamstrings/world-greatest-stretch",
        "shoulder" to "delts/dumbbell-reverse-fly",
        "sit wall" to "quads/all-fours-squad-stretch",
        "skater" to "cardio/skater-hops",
        "sprint treadmill" to "cardio/walking-on-incline-treadmill",
        "step ups" to "glutes/dumbbell-step-up",
        "strength upper" to "hamstrings/world-greatest-stretch",
        "stretching" to "hamstrings/world-greatest-stretch",
        "sunday" to "hamstrings/world-greatest-stretch",
        "superman" to "pectorals/superman-push-up",
        "thursday" to "hamstrings/world-greatest-stretch",
        "today" to "hamstrings/world-greatest-stretch",
        "tomorrow" to "upper-back/upper-back-stretch",
        "tuesday" to "hamstrings/world-greatest-stretch",
        "upper" to "hamstrings/world-greatest-stretch",
        "walk" to "glutes/monster-walk",
        "wednesday" to "hamstrings/world-greatest-stretch",
        "yesterday" to "hamstrings/world-greatest-stretch",
    )

    /** Canonical key matching the generator: lower-case, strip apostrophes/punct, singularise, sort. */
    private fun canon(name: String): String {
        val cleaned = name.lowercase().replace(Regex("['’]"), "").replace(Regex("[^a-z0-9]+"), " ").trim()
        if (cleaned.isEmpty()) return ""
        return cleaned.split(Regex("\\s+"))
            .map { w -> if (w.length > 3 && w.endsWith("s") && !w.endsWith("ss")) w.dropLast(1) else w }
            .filter { it.isNotEmpty() && it !in stop }
            .sorted()
            .joinToString(" ")
    }

    /** Animated GIF url for an exercise name, or null when we have no demo (→ diagram fallback). */
    fun gifUrl(name: String): String? {
        val id = ids[canon(name)] ?: return null
        return BASE + id + ".gif"
    }
}
