package com.nutriai.ui.move

// AUTO-GENERATED: free-exercise-db (public domain) slug per exercise name. Two stills per exercise
// (0.jpg start, 1.jpg end) are alternated client-side into an animated movement demo. Keys are
// lower-cased exercise names; unmatched exercises fall back to the bundled muscle diagram.
object ExerciseDemoMap {
    const val BASE = "https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises/"
    private val slugs: Map<String, String> = mapOf(
        "ab wheel rollout" to "Barbell_Ab_Rollout",
        "archer push-ups" to "Pushups",
        "arnold press" to "Arnold_Dumbbell_Press",
        "back squat" to "Barbell_Squat",
        "backpack high-row" to "Seated_Cable_Rows",
        "backpack rows" to "Seated_Cable_Rows",
        "backpack shrugs" to "Cable_Shrugs",
        "band chest press" to "Cable_Chest_Press",
        "band good-mornings" to "Seated_Good_Mornings",
        "band rows" to "Seated_Cable_Rows",
        "band-assisted pull-ups" to "Band_Assisted_Pull-Up",
        "barbell bench press" to "Barbell_Bench_Press_-_Medium_Grip",
        "barbell curl" to "Barbell_Curl",
        "barbell deadlift" to "Barbell_Deadlift",
        "barbell lunge" to "Barbell_Lunge",
        "barbell row" to "Bent_Over_Barbell_Row",
        "barbell shrugs" to "Barbell_Shrug",
        "bench dips" to "Bench_Dips",
        "bench press" to "Barbell_Bench_Press_-_Medium_Grip",
        "bicycle crunch" to "Air_Bike",
        "bicycle crunches" to "Air_Bike",
        "bodyweight / goblet squats" to "Bodyweight_Squat",
        "bodyweight squats" to "Bodyweight_Squat",
        "box jumps" to "Box_Jump_Multiple_Response",
        "bulgarian split squat" to "Barbell_Side_Split_Squat",
        "bulgarian split squat (chair)" to "Barbell_Side_Split_Squat",
        "cable crossover" to "Cable_Crossover",
        "cable crunch" to "Cable_Crunch",
        "cable fly" to "Cable_Crossover",
        "cable lateral raise" to "Side_Lateral_Raise",
        "cable overhead extension" to "Cable_Rope_Overhead_Triceps_Extension",
        "cable row" to "Seated_Cable_Rows",
        "calf raise" to "Standing_Calf_Raises",
        "calf raises" to "Standing_Calf_Raises",
        "chair dips" to "Bench_Dips",
        "chest dips" to "Dips_-_Chest_Version",
        "chest-supported row" to "Seated_Cable_Rows",
        "clap push-ups" to "Pushups",
        "close-grip bench press" to "Close-Grip_Barbell_Bench_Press",
        "close-grip push-ups" to "Pushups",
        "concentration curl" to "Concentration_Curls",
        "cross-body shoulder stretch" to "Shoulder_Stretch",
        "crunch" to "Crunches",
        "crunches" to "Crunches",
        "curtsy lunges" to "Bodyweight_Walking_Lunge",
        "dead bug" to "Dead_Bug",
        "dead bugs" to "Dead_Bug",
        "deadlift" to "Barbell_Deadlift",
        "decline press" to "Decline_Barbell_Bench_Press",
        "decline push-ups" to "Pushups",
        "diamond push-ups" to "Pushups",
        "doorway rows" to "Seated_Cable_Rows",
        "dumbbell bench press" to "Dumbbell_Bench_Press",
        "dumbbell curl" to "Dumbbell_Bicep_Curl",
        "dumbbell curls" to "Dumbbell_Bicep_Curl",
        "dumbbell press" to "Dumbbell_Bench_Press",
        "dumbbell shoulder press" to "Dumbbell_Shoulder_Press",
        "dumbbell shrugs" to "Dumbbell_Shrug",
        "ez-bar curl" to "EZ-Bar_Curl",
        "face pull" to "Face_Pull",
        "feet-elevated push-ups" to "Pushups",
        "flat dumbbell press" to "Dumbbell_Bench_Press",
        "flutter kicks" to "Flutter_Kicks",
        "front raise" to "Front_Dumbbell_Raise",
        "front squat" to "Front_Barbell_Squat",
        "glute bridge" to "Butt_Lift_Bridge",
        "glute bridges" to "Butt_Lift_Bridge",
        "goblet squat" to "Goblet_Squat",
        "good morning" to "Good_Morning",
        "good mornings" to "Good_Morning",
        "hack squat" to "Hack_Squat",
        "hammer curl" to "Hammer_Curls",
        "hammer curls (backpack)" to "Alternate_Hammer_Curl",
        "hanging knee raise" to "Hanging_Leg_Raise",
        "hanging leg raise" to "Hanging_Leg_Raise",
        "hanging/lying leg raises" to "Hanging_Leg_Raise",
        "hindu push-ups" to "Pushups",
        "hip thrusts" to "Barbell_Hip_Thrust",
        "hip thrusts / glute bridges (back-friendly)" to "Barbell_Hip_Thrust",
        "incline barbell press" to "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "incline cable press" to "Incline_Cable_Chest_Press",
        "incline dumbbell curl" to "Alternate_Incline_Dumbbell_Curl",
        "incline dumbbell press" to "Incline_Dumbbell_Press",
        "incline press" to "Barbell_Incline_Bench_Press_-_Medium_Grip",
        "incline push-ups (hands on a surface)" to "Pushups",
        "inverted rows" to "Inverted_Row",
        "jm press" to "JM_Press",
        "jump lunges" to "Bodyweight_Walking_Lunge",
        "jump squats" to "Freehand_Jump_Squat",
        "kettlebell swings" to "One-Arm_Kettlebell_Swings",
        "knee push-ups" to "Pushups",
        "lat pulldown" to "One_Arm_Lat_Pulldown",
        "lat pulldown with a band" to "One_Arm_Lat_Pulldown",
        "lateral raise" to "Side_Lateral_Raise",
        "leg curl" to "Seated_Leg_Curl",
        "leg extension" to "Single-Leg_Leg_Extension",
        "leg press" to "Leg_Press",
        "leg raises" to "Flat_Bench_Lying_Leg_Raise",
        "machine chest press" to "Cable_Chest_Press",
        "machine shoulder press" to "Alternating_Cable_Shoulder_Press",
        "mountain climbers" to "Mountain_Climbers",
        "overhead barbell press" to "Barbell_Shoulder_Press",
        "overhead extension" to "Cable_Rope_Overhead_Triceps_Extension",
        "pike push-ups" to "Pushups",
        "pistol squat (assisted)" to "Kettlebell_Pistol_Squat",
        "plank" to "Plank",
        "preacher curl" to "Cable_Preacher_Curl",
        "pseudo-planche push-ups" to "Pushups",
        "pull (back / biceps)" to "Seated_Biceps",
        "pull-ups (weighted)" to "Weighted_Pull_Ups",
        "push press" to "Push_Press",
        "push-up burnout" to "Pushups",
        "push-ups" to "Pushups",
        "push-ups (feet elevated to progress)" to "Pushups",
        "rack pulls" to "Rack_Pulls",
        "rear-delt fly" to "Cable_Rear_Delt_Fly",
        "rear-delt row" to "Barbell_Rear_Delt_Row",
        "resistance-band chest press" to "Cable_Chest_Press",
        "reverse curl" to "Reverse_Cable_Curl",
        "reverse lunges" to "Bodyweight_Walking_Lunge",
        "reverse lunges (knee-friendly)" to "Bodyweight_Walking_Lunge",
        "reverse wrist curl" to "Cable_Wrist_Curl",
        "romanian deadlift" to "Romanian_Deadlift",
        "rope hammer curl" to "Cable_Hammer_Curls_-_Rope_Attachment",
        "rope pushdown" to "Triceps_Pushdown_-_Rope_Attachment",
        "russian twist" to "Russian_Twist",
        "russian twists" to "Russian_Twist",
        "scapular push-ups" to "Pushups",
        "seated cable row" to "Seated_Cable_Rows",
        "seated calf raise" to "Seated_Calf_Raise",
        "seated row" to "Seated_Cable_Rows",
        "side plank" to "Push_Up_to_Side_Plank",
        "single-arm dumbbell row" to "One-Arm_Dumbbell_Row",
        "single-leg glute bridge" to "Single_Leg_Glute_Bridge",
        "slow push-ups (3s down)" to "Pushups",
        "spider curl" to "Spider_Curl",
        "standing calf raise" to "Standing_Calf_Raises",
        "standing knee raises" to "Bent-Knee_Hip_Raise",
        "standing quad stretch" to "Quad_Stretch",
        "step ups" to "Dumbbell_Step_Ups",
        "step-ups" to "Dumbbell_Step_Ups",
        "straight-arm pulldown" to "Straight-Arm_Pulldown",
        "superman" to "Superman",
        "supermans" to "Superman",
        "svend press" to "Svend_Press",
        "t-bar row" to "Lying_T-Bar_Row",
        "towel door rows" to "Seated_Cable_Rows",
        "trap-bar deadlift" to "Trap_Bar_Deadlift",
        "upright row" to "Upright_Cable_Row",
        "walking lunges" to "Bodyweight_Walking_Lunge",
        "weighted dips" to "Weighted_Bench_Dip",
        "weighted pull-ups" to "Weighted_Pull_Ups",
        "wide push-ups" to "Pushups",
        "wide-grip pulldown" to "Wide-Grip_Lat_Pulldown",
        "wrist curl" to "Cable_Wrist_Curl",
        "zottman curl" to "Zottman_Curl",
    )

    /** [startUrl, endUrl] for an exercise name, or null when we have no demo for it. */
    fun framesFor(name: String): Pair<String, String>? {
        val slug = slugs[name.trim().lowercase()] ?: return null
        return (BASE + slug + "/0.jpg") to (BASE + slug + "/1.jpg")
    }
}
